### ISSUE TITLE
Hi, there! Looking forward to your code

### ISSUE THREAD

**Issue by yuchenlichuck** [diegovalsesia/HyCoRe#1]

**Comment by ark1234** [comment]
Me too!

**Comment by diegovalsesia** [comment]
Code published. Let us know in case of issues. The code is largely based on the PointMLP repo (https://github.com/ma-xu/pointMLP-pytorch), so make sure to check the issues there in case of environment/compilation problems. Links to checkpoints for pretrained models will be published soon.
